<?php
/**
 * Created by PhpStorm.
 * User: HP ELITEBOOK 840 G5
 * Date: 1/30/2020
 * Time: 3:45 PM
 */

namespace frontend\controllers;


use common\models\User;

class AccountController extends \yii\rest\ActiveController
{
    public $modelClass = User::class;

    //my custom action just to return an access token

    public function actionToken(){
        return ['token' => $this->access_token];
    }


    /**
     * @param string $action
     * @param User $model
     * @param array $params
     */
    public function checkAccess($action, $model = null, $params = [])
    {
        //parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
        if(in_array($action,['token']) && !$model->access_token ){
            throw new ForbiddenHttpException('You have are no a valid user, sign up to get an access token');
        }
    }
}