<?php
/**
 * Created by PhpStorm.
 * User: HP ELITEBOOK 840 G5
 * Date: 1/30/2020
 * Time: 2:05 PM
 */

namespace frontend\controllers;


use frontend\resource\Post;
use yii\filters\auth\HttpBearerAuth;

class ActiveController extends \yii\rest\ActiveController
{
    public function behaviors()
    {
        //Api authentication
        $behaviours =  parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviours['authenticator']['only'] = ['create','update','delete'];
        $behaviours['authenticator']['authMethods'] = [
            HttpBearerAuth::class
        ];

        return $behaviours;
    }

    //Api authorization
    //Override checkAccess method from ActiveController

    /**
     * @param string $action
     * @param Comment | Post $model
     * @throws ForbiddenHttpException
     * @param array $params
     */
    public function checkAccess($action, $model = null, $params = [])
    {
        //parent::checkAccess($action, $model, $params); // TODO: Change the autogenerated stub
        if(in_array($action,['update','delete']) && $model->created_by !== \Yii::$app->user->id){
            throw new ForbiddenHttpException('You have no permission to alter this record.');
        }
    }

}