<?php
/**
 * Created by PhpStorm.
 * User: HP ELITEBOOK 840 G5
 * Date: 1/29/2020
 * Time: 2:43 PM
 */

namespace frontend\resource;


class Post extends \common\models\Post
{
    public function fields()
    {
        //return parent::fields(); // TODO: Change the autogenerated stub
        return ['id','title','body'];
    }

    public function extraFields()
    {
        return ['comments','created_at', 'updated_at'];
    }


    /* Override the getComment relation to use the resource comments class*/
    public function getComments()
    {
        return $this->hasMany(Comment::class, ['post_id' => 'id']);
    }
}